---
title: "Ne_RCCR_plot"
author: "Idalia Rojas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
#setworking directory
# Getting the path of your current open file
current_path = rstudioapi::getActiveDocumentContext()$path 
setwd(dirname(current_path ))
print( getwd() )

#libraries
library(tidyverse)
library(data.table)
library(RColorBrewer)
```

## Load CCR for Aegilops and 

```{r load.data}
#Load csv files
files <- list.files(path = "./../data/msmc_16hap/",
                    pattern = "final.txt", 
                    full.names = T)

#Make a data frame for the diifereent haplotype combinations
ccr <- rbindlist(sapply(files, fread,simplify = FALSE), idcol = 'filename')

#Make a column with haplotype combination ID
ccr$hap<-gsub("./../data/msmc_16hap//combined_wht-aeg_16hap_msmc.","",as.character(ccr$filename))
ccr$hap<-gsub(".final.txt","",as.character(ccr$hap))


```

Compute Time and ccr per haplotype 
```{r group}

ccr$Time <- unlist(ccr %>% 
  group_by(hap) %>% 
  group_map (~(.x$left_time_boundary + .x$right_time_boundary)/2))

ccr$rccr <- unlist(ccr %>% 
  group_by(hap) %>% 
  group_map (~((2*.x$lambda_01)/(.x$lambda_00+.x$lambda_11))))

```
Define mutation rate (u) and generations (g) parameters
```{r data}
#Mutation rate
u <- 3.3e-8 #(Lynch et al 2008)
g <- 0.5  #1 generation per year

#Define pallete


myPalette <- colorRampPalette(rev(brewer.pal(11, "BuPu")))
sc <- scale_colour_gradientn(colours = myPalette(100), limits=c(0,2))

#Plot replicates
p.cross <- ggplot(ccr, aes( x = Time *g/u/1000, y = rccr, group = hap))+
  annotate ("rect", xmin = 9, xmax = 10, ymin = 0, ymax = 1, fill = gray(0.5))+
  geom_line(aes(col = rccr), size = 0.5)+ sc+
  scale_x_continuous( trans = "log10",
                      breaks = c(1, 10, 100, 1000),
                      minor_breaks = c(0.5, 1, 5, 50, 500),
                      labels = scales::comma_format(accuracy = 0.1))+
  ylab(expression(rccr)) + xlab("Time (ky)")+
  ggtitle("Aegilops vs Triticum (mu = 3.3e-8, 1 gen/year)") +
  ylab ("RCCR")#+
#geom_hline(yintercept = 0.5, color = "brown")

p.cross 

png("../plots/rccr_AegWht.png", height = 400, width = 600 )
p.cross
dev.off()

```
```{r Ne.aeg}

#Load csv files
files <- list.files(path = "./../data/aeg",
                    pattern = "final.txt", 
                    full.names = T)

#Make a data frame for the diifereent haplotype combinations
aeg <- rbindlist(sapply(files, fread,simplify = FALSE), idcol = 'filename')

#Make a column with haplotype combination ID
aeg$hap<-gsub("./../data/aeg/aeg.16hapl.allChr.within-","",as.character(aeg$filename))
aeg$hap<-gsub(".output.final.txt","",as.character(aeg$hap))
  
  
aeg$Time <- unlist(aeg %>% 
  group_by(hap) %>% 
  group_map(~(.x$left_time_boundary/u*g)))

aeg$Ne <- unlist(aeg %>% 
   group_by(hap) %>% 
  group_map (~(1/.x$lambda)/(2*u)))
 
#aeg <- aeg[!grepl("pop1.comb6", aeg$hap),]

```
Plot Ne replicates

```{r Ne.plot}
#Plot replicates
p.aeg <- ggplot(aeg, aes( x = Time/1000, y = Ne, group = hap))+
  annotate ("rect", xmin = 9, xmax = 10, ymin = 0, ymax = 1000000, fill = gray(0.5))+
  geom_step(aes(col = Ne), size = 0.5)+ 
  scale_x_continuous( trans = "log10",
                      breaks = c(1, 10, 100, 1000),
                      minor_breaks = c(0.5, 1, 5, 50, 500),
                      labels = scales::comma_format(accuracy = 0.1))+
  scale_y_continuous(trans = "log10",
                     breaks = c(1000, 10000,100000, 1000000)
                 )+
  ylab(expression(rccr)) + xlab("Time (ky)")+
  ggtitle("Aegilops (mu = 3.3e-8), 1 gen/year") +

  ylab ("Ne")#+
#geom_hline(yintercept = 0.5, color = "brown")

p.aeg

png("../plots/NeAeg.png", height = 400, width = 600 )
p.aeg
dev.off()

```
Load files for the Triticum-infecting population
```{r  Ne.wht}


#Load csv files
files <- list.files(path = "./../data/wht",
                    pattern = "final.txt", 
                    full.names = T)

#Make a data frame for the diifereent haplotype combinations
wht <- rbindlist(sapply(files, fread,simplify = FALSE), idcol = 'filename')

#Make a column with haplotype combination ID
wht$hap<-gsub("./../data/wht/wht.16hapl.allChr.within-","",as.character(wht$filename))
wht$hap<-gsub(".output.final.txt","",as.character(wht$hap))
  
  
wht$Time <- unlist(wht %>% 
  group_by(hap) %>% 
  group_map(~(.x$left_time_boundary/u*g)))

wht$Ne <- unlist(wht %>% 
   group_by(hap) %>% 
  group_map (~(1/.x$lambda)/(2*u)))
 
#wht <- wht[!grepl("pop1.comb6", aeg$hap),]

```

Plot Ne for wheat
```{r NeWht.plot}

p.wht <- ggplot(wht, aes( x = Time/1000, y = Ne, group = hap))+
  annotate ("rect", xmin = 9, xmax = 10, ymin = 0, ymax = 1000000, fill = gray(0.5))+
  geom_step(aes(col = Ne), size = 0.5)+ 
  scale_x_continuous( trans = "log10",
                      breaks = c(1, 10, 100, 1000),
                      minor_breaks = c(0.25,0.5, 1, 5, 50, 500),
                      labels = scales::comma_format(accuracy = 0.1))+
  scale_y_continuous(trans = "log10",
                     breaks = c(1000, 10000,100000, 1000000)
                 )+
  ylab(expression(rccr)) + xlab("Time (ky)")+
  ggtitle("Triticum (mu = 3.3e-8, 1 gen/year)") +

  ylab ("Ne")#+
#geom_hline(yintercept = 0.5, color = "brown")

p.wht
png("../plots/NeWht.png", height = 400, width = 600 )
p.wht
dev.off()

```
